"""auto_migration_20250408_034101

Revision ID: 6d4c46f04333
Revises: bd5ea5a256d8
Create Date: 2025-04-08 03:41:02.008015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4c46f04333'
down_revision: Union[str, None] = 'bd5ea5a256d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khachhang',
    sa.Column('MaKH', sa.String(length=10), nullable=False),
    sa.Column('TenKH', sa.String(length=100), nullable=False),
    sa.Column('DiaChi', sa.String(length=150), nullable=False),
    sa.Column('SDT', sa.String(length=10), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('MaSoThue', sa.String(length=15), nullable=True),
    sa.Column('PhanLoai', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('MaKH', 'id')
    )
    op.create_index(op.f('ix_khachhang_MaKH'), 'khachhang', ['MaKH'], unique=False)
    op.create_index(op.f('ix_khachhang_MaSoThue'), 'khachhang', ['MaSoThue'], unique=False)
    op.create_index(op.f('ix_khachhang_id'), 'khachhang', ['id'], unique=False)
    op.create_table('spdv',
    sa.Column('MaSPDV', sa.String(length=10), nullable=False),
    sa.Column('TenSPDV', sa.String(length=100), nullable=False),
    sa.Column('DonGia', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('DVT', sa.String(length=10), nullable=False),
    sa.Column('MoTa', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('MaSPDV', 'id')
    )
    op.create_index(op.f('ix_spdv_MaSPDV'), 'spdv', ['MaSPDV'], unique=False)
    op.create_index(op.f('ix_spdv_id'), 'spdv', ['id'], unique=False)
    op.create_table('tkkt',
    sa.Column('MaTK', sa.String(length=10), nullable=False),
    sa.Column('TenTK', sa.String(length=100), nullable=False),
    sa.Column('CapTK', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('MaTK', 'id')
    )
    op.create_index(op.f('ix_tkkt_MaTK'), 'tkkt', ['MaTK'], unique=False)
    op.create_index(op.f('ix_tkkt_id'), 'tkkt', ['id'], unique=False)
    op.create_table('banggia',
    sa.Column('MaSPDV', sa.String(length=10), nullable=False),
    sa.Column('NgayHL', sa.DateTime(), nullable=False),
    sa.Column('GiaBan', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaSPDV'], ['spdv.MaSPDV'], ),
    sa.PrimaryKeyConstraint('MaSPDV', 'NgayHL', 'id')
    )
    op.create_index(op.f('ix_banggia_id'), 'banggia', ['id'], unique=False)
    op.create_table('dinhmucck',
    sa.Column('MaSPDV', sa.String(length=10), nullable=False),
    sa.Column('NgayHL', sa.DateTime(), nullable=False),
    sa.Column('MucTien', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('TyLeCK', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaSPDV'], ['spdv.MaSPDV'], ),
    sa.PrimaryKeyConstraint('MaSPDV', 'NgayHL', 'id')
    )
    op.create_index(op.f('ix_dinhmucck_id'), 'dinhmucck', ['id'], unique=False)
    op.create_table('hoadon',
    sa.Column('SoCT', sa.String(length=10), nullable=False),
    sa.Column('NgayLap', sa.DateTime(), nullable=False),
    sa.Column('MaKH', sa.String(length=10), nullable=False),
    sa.Column('TenKH', sa.String(length=150), nullable=False),
    sa.Column('HinhThucTT', sa.String(length=50), nullable=False),
    sa.Column('TKNo', sa.String(length=10), nullable=False),
    sa.Column('DienGiai', sa.Text(), nullable=True),
    sa.Column('TKCoDT', sa.String(length=10), nullable=False),
    sa.Column('TKCoThue', sa.String(length=10), nullable=False),
    sa.Column('ThueSuat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('TienThue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('TyLeCK', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('TKChietKhau', sa.String(length=10), nullable=True),
    sa.Column('TienCK', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('TienDT', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('TienTT', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaKH'], ['khachhang.MaKH'], ),
    sa.ForeignKeyConstraint(['TKChietKhau'], ['tkkt.MaTK'], ),
    sa.ForeignKeyConstraint(['TKCoDT'], ['tkkt.MaTK'], ),
    sa.ForeignKeyConstraint(['TKCoThue'], ['tkkt.MaTK'], ),
    sa.ForeignKeyConstraint(['TKNo'], ['tkkt.MaTK'], ),
    sa.PrimaryKeyConstraint('SoCT', 'id')
    )
    op.create_index(op.f('ix_hoadon_MaKH'), 'hoadon', ['MaKH'], unique=False)
    op.create_index(op.f('ix_hoadon_NgayLap'), 'hoadon', ['NgayLap'], unique=False)
    op.create_index(op.f('ix_hoadon_SoCT'), 'hoadon', ['SoCT'], unique=False)
    op.create_index(op.f('ix_hoadon_id'), 'hoadon', ['id'], unique=False)
    op.create_table('ct_hoadon',
    sa.Column('SoCT', sa.String(length=10), nullable=False),
    sa.Column('MaSPDV', sa.String(length=10), nullable=False),
    sa.Column('SoLuong', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('DVT', sa.String(length=10), nullable=False),
    sa.Column('DonGia', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaSPDV'], ['spdv.MaSPDV'], ),
    sa.ForeignKeyConstraint(['SoCT'], ['hoadon.SoCT'], ),
    sa.PrimaryKeyConstraint('SoCT', 'MaSPDV', 'id')
    )
    op.create_index(op.f('ix_ct_hoadon_id'), 'ct_hoadon', ['id'], unique=False)
    op.create_table('phieugiamgia',
    sa.Column('SoPhieu', sa.String(length=10), nullable=False),
    sa.Column('NgayLap', sa.DateTime(), nullable=False),
    sa.Column('MaKH', sa.String(length=10), nullable=False),
    sa.Column('DienGiai', sa.Text(), nullable=True),
    sa.Column('TKNoGiamTru', sa.String(length=10), nullable=False),
    sa.Column('TKCoTT', sa.String(length=10), nullable=False),
    sa.Column('SoCT', sa.String(length=10), nullable=False),
    sa.Column('ThueSuat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('TienThue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('TKNoThue', sa.String(length=10), nullable=False),
    sa.Column('TienDT', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('TienTT', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaKH'], ['khachhang.MaKH'], ),
    sa.ForeignKeyConstraint(['SoCT'], ['hoadon.SoCT'], ),
    sa.ForeignKeyConstraint(['TKCoTT'], ['tkkt.MaTK'], ),
    sa.ForeignKeyConstraint(['TKNoGiamTru'], ['tkkt.MaTK'], ),
    sa.ForeignKeyConstraint(['TKNoThue'], ['tkkt.MaTK'], ),
    sa.PrimaryKeyConstraint('SoPhieu', 'id')
    )
    op.create_index(op.f('ix_phieugiamgia_MaKH'), 'phieugiamgia', ['MaKH'], unique=False)
    op.create_index(op.f('ix_phieugiamgia_NgayLap'), 'phieugiamgia', ['NgayLap'], unique=False)
    op.create_index(op.f('ix_phieugiamgia_SoCT'), 'phieugiamgia', ['SoCT'], unique=False)
    op.create_index(op.f('ix_phieugiamgia_SoPhieu'), 'phieugiamgia', ['SoPhieu'], unique=False)
    op.create_index(op.f('ix_phieugiamgia_id'), 'phieugiamgia', ['id'], unique=False)
    op.create_table('ct_phieu',
    sa.Column('SoPhieu', sa.String(length=10), nullable=False),
    sa.Column('MaSPDV', sa.String(length=10), nullable=False),
    sa.Column('SoLuong', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('DVT', sa.String(length=10), nullable=False),
    sa.Column('DonGia', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaSPDV'], ['spdv.MaSPDV'], ),
    sa.ForeignKeyConstraint(['SoPhieu'], ['phieugiamgia.SoPhieu'], ),
    sa.PrimaryKeyConstraint('SoPhieu', 'MaSPDV', 'id')
    )
    op.create_index(op.f('ix_ct_phieu_id'), 'ct_phieu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ct_phieu_id'), table_name='ct_phieu')
    op.drop_table('ct_phieu')
    op.drop_index(op.f('ix_phieugiamgia_id'), table_name='phieugiamgia')
    op.drop_index(op.f('ix_phieugiamgia_SoPhieu'), table_name='phieugiamgia')
    op.drop_index(op.f('ix_phieugiamgia_SoCT'), table_name='phieugiamgia')
    op.drop_index(op.f('ix_phieugiamgia_NgayLap'), table_name='phieugiamgia')
    op.drop_index(op.f('ix_phieugiamgia_MaKH'), table_name='phieugiamgia')
    op.drop_table('phieugiamgia')
    op.drop_index(op.f('ix_ct_hoadon_id'), table_name='ct_hoadon')
    op.drop_table('ct_hoadon')
    op.drop_index(op.f('ix_hoadon_id'), table_name='hoadon')
    op.drop_index(op.f('ix_hoadon_SoCT'), table_name='hoadon')
    op.drop_index(op.f('ix_hoadon_NgayLap'), table_name='hoadon')
    op.drop_index(op.f('ix_hoadon_MaKH'), table_name='hoadon')
    op.drop_table('hoadon')
    op.drop_index(op.f('ix_dinhmucck_id'), table_name='dinhmucck')
    op.drop_table('dinhmucck')
    op.drop_index(op.f('ix_banggia_id'), table_name='banggia')
    op.drop_table('banggia')
    op.drop_index(op.f('ix_tkkt_id'), table_name='tkkt')
    op.drop_index(op.f('ix_tkkt_MaTK'), table_name='tkkt')
    op.drop_table('tkkt')
    op.drop_index(op.f('ix_spdv_id'), table_name='spdv')
    op.drop_index(op.f('ix_spdv_MaSPDV'), table_name='spdv')
    op.drop_table('spdv')
    op.drop_index(op.f('ix_khachhang_id'), table_name='khachhang')
    op.drop_index(op.f('ix_khachhang_MaSoThue'), table_name='khachhang')
    op.drop_index(op.f('ix_khachhang_MaKH'), table_name='khachhang')
    op.drop_table('khachhang')
    # ### end Alembic commands ###
