from app.models.user import User
from app.models.khachhang import KhachHang
from app.models.spdv import SPDV
from app.models.tkkt import TKKT
from app.models.banggia import BangGia
from app.models.dinhmucck import DinhMucCK
from app.models.hoadon import HoaDon
from app.models.ct_hoadon  import CTHoaDon
from app.models.phieugiamgia import PhieuGiamGia
from app.models.ct_phieu import CTPhieu